### ISSUE TITLE
URL Analysis Problem

### ISSUE THREAD

**Issue by seantree** [ctxis/CAPE#31] opened 2018-03-06 10:25 UTC
Hi @kevoreilly 

I am analysing following links but it's not analyzing, it's a kind of BHO when a user access the following links and it contains the button on page which install extension/addon in the browser. When I submit these links to the sandbox it just opens the links in the browser nothing else it does. Kindly tell me the way please?
hxxp://watchingnewsonline.com/
hxxp://yourmapview.com/
hxxp://easycouponsaccess.com/
hxxp://www.propdfconverter.com/index.jhtml
hxxp://www.gamesquest.co/
hxxp://loginemailsfast.com/
hxxp://emailloginnow.com/Email?

hxxp://www.searchtuner.com/download/?offer_id=712&aff_id=5&url_id=962&source=1319268&aff_sub2=425312588801&ot=1&sah=728&cw=1366&nw=0

hxxp://screenwatch.yournewtab.com/?chid=127&oid=706&pubid=1319268&subid=425321025281&sah=728&cw=1366&nw=0

 hxxp://watchmoretvnow.com/
hxxp://www.todaysnewsreporter.com/
hxxp://www.checknetspeed.online/li1tg?t1=test&t5={Browser}&cid=clk_id

hxxp://www.checkmyspeed.co/bir14?t1=S_Restructure_Test&t2={adgroup_name}&t3=speedtest%20net&t4=1t1&t5=250999826041&gclid=EAIaIQobChMIo_Wuq--72QIVl7rACh1tQAnzEAAYASAAEgIBkPD_BwE

hxxp://www.watchtvinstantly.com/?r=3&kw=Weather%20Season&gclid=EAIaIQobChMIhvatk7Of1gIVDLcbCh11UgoiEAAYAyAAEgJ9APD_BwE

hxxp://www.getsports.net/
hxxp://www.moviesearch.today/

.
Thanks & Regards
Seantree

**Comment by kevoreilly** [comment] 2018-03-07 11:02
I would say the first thing to check is that the URLs are launched in a browser package whether this be for IE, Firefox or Chrome. You should then verify that the behavioural analysis has occured in the resulting output, with API calls from the browser process appearing. If not this can perhaps be diagnosed by looking in the analysis log.

**Comment by kevoreilly** [comment] 2018-03-07 11:03
Also, if these links are in any way dodgy it's probably best not to paste them directly into comments as anyone could click on them outside of a sandbox and end up in trouble.

**Comment by seantree** [comment] 2018-03-07 11:18
Hi @kevoreilly these links are launching in a browser when the page is accessed by the browser in sandbox it doesn't click on the buttons and all the above links are only like this. it needs human interaction to click on the button to each time. All these links contains addons which needs human interaction and yeah I forgot to edit these links, kindly throw these links in your sandbox, you will understand what they right now happening.

**Comment by kevoreilly** [comment] 2018-03-07 11:26
Have you had any luck getting the analysis working?

**Comment by seantree** [comment] 2018-03-07 12:08
no not yet that's why I gave these links, so that you can check and help it.

**Comment by kevoreilly** [comment] 2018-03-07 12:10
Did you see my points about checking the package, behavioural analysis output, analysis log, etc.

**Comment by seantree** [comment] 2018-03-07 12:11
Yes I checked all the points before

**Comment by kevoreilly** [comment] 2018-03-07 12:12
I was hoping for some more information from these sources in order to try and help diagnose what is going on.

**Comment by kevoreilly** [comment] 2018-03-07 12:29
Aha! This sounds like a limitation in the automated interaction which is governed by the 'human' auxiliary module: analyzer/windows/modules/auxiliary/human.py

This module contains, among other things, lists of buttons to click or not to click. Perhaps with an appropriate addition here you will succeed in automating the clicking of the right box to trigger the download you are after.

**Comment by seantree** [comment] 2018-03-07 12:32
I know about this file and I tried also but for web pages they are not working

**Comment by kevoreilly** [comment] 2018-03-07 12:53
This is a question then of automated web/browser interaction which is beyond the scope of what I think was intended with the human auxiliary module. Nonetheless it may be possible to add to this module or create another one for this purpose, perhaps taking inspiration from projects like Splinter (https://github.com/cobrateam/splinter) which let you automate browser actions, such interacting with web pages.

**Comment by doomedraven** [comment] 2018-03-07 15:23
im sure there much more priorities, but you always can PR working poc to speedup integration :)

**Comment by kevoreilly** [comment] 2018-03-19 14:07
Closing this now - it's more of a feature request than an issue - maybe someone down the line will contribute automated browser interaction.

**Closed by kevoreilly** 2018-03-19 14:07 UTC
