### ISSUE TITLE
API failure when getting json from a request

### ISSUE THREAD

**Issue by mjcuchillo** [ctxis/CAPE#83] opened 2018-08-27 10:23 UTC
When I try to make a request using the API to obtain the json report, the response is:
{
    "error_value": "Reports directory does not exist", 
    "error": true
}
I have tried several examples and all of them have the same response. Some examples are: 
https://cape.contextis.com/api/tasks/get/report/15965/json/
https://cape.contextis.com/api/tasks/get/report/15952/json/

Thank you in advance! I hope you can help me.

**Comment by redsand** [comment] 2018-09-14 14:41
Hi,
This means the file: /home/cuckoo/CAPE/storage/analyses/15965/reports/report.json does not exist on disk.  This is not a bug, rather the public demo does not have JSON reporting option turned on.  This can be closed as it is working as expected.

**Comment by kevoreilly** [comment] 2018-09-14 15:40
Yes indeed - thanks for clarifying!

**Closed by kevoreilly** 2018-09-14 15:40 UTC
