### ISSUE TITLE
Newly submitted URLs not being analyzed in CAPE Sandbox

### ISSUE THREAD

**Issue by KindaTerrible** [ctxis/CAPE#379] opened 2019-08-08 19:47 UTC
I recently discovered and wanted to test out CAPE sandbox on my own. Setting up and installation was straight forward and I got everything working (supposedly). I submitted a URL I got from the Malware Domain list to test, and then every URL I submit after does not get put into IE to run in the sandbox. Instead it keeps running the first URL I submitted and spitting out the same results each time.

Logs are below (submitted URL has been defanged in the logs below to prevent accidental clicks)

> 2019-08-08 17:43:36,000 [root] INFO: Date set to: 08-08-19, time set to: 17:43:36, timeout set to: 200
> 2019-08-08 17:43:36,015 [root] DEBUG: Starting analyzer from: C:\mucvbxfoni
> 2019-08-08 17:43:36,015 [root] DEBUG: Storing results at: C:\irYjEH
> 2019-08-08 17:43:36,015 [root] DEBUG: Pipe server name: \\.\PIPE\KqHrJn
> 2019-08-08 17:43:36,015 [root] DEBUG: No analysis package specified, trying to detect it automagically.
> 2019-08-08 17:43:36,030 [root] INFO: Automatically selected analysis package "ie"
> 2019-08-08 17:43:36,280 [root] DEBUG: Started auxiliary module Browser
> 2019-08-08 17:43:36,280 [root] DEBUG: Started auxiliary module Curtain
> 2019-08-08 17:43:36,280 [modules.auxiliary.digisig] DEBUG: Skipping authenticode validation, analysis is not a file.
> 2019-08-08 17:43:36,280 [root] DEBUG: Started auxiliary module DigiSig
> 2019-08-08 17:43:36,280 [root] DEBUG: Started auxiliary module Disguise
> 2019-08-08 17:43:36,280 [root] DEBUG: Started auxiliary module Human
> 2019-08-08 17:43:36,280 [root] DEBUG: Started auxiliary module Screenshots
> 2019-08-08 17:43:36,280 [root] DEBUG: Started auxiliary module Sysmon
> 2019-08-08 17:43:36,296 [root] DEBUG: Started auxiliary module Usage
> 2019-08-08 17:43:36,296 [root] INFO: Analyzer: Package modules.packages.ie does not specify a DLL option
> 2019-08-08 17:43:36,296 [root] INFO: Analyzer: Package modules.packages.ie does not specify a DLL_64 option
> 2019-08-08 17:43:36,328 [lib.api.process] INFO: Successfully executed process from path "C:\Program Files (x86)\Internet Explorer\iexplore.exe" with arguments ""textspeier[.]de"" with pid 2896
> 2019-08-08 17:43:36,342 [lib.api.process] INFO: Option 'nohuman' with value 'yes' sent to monitor
> 2019-08-08 17:43:36,342 [lib.api.process] INFO: Option 'procdump' with value '1' sent to monitor
> 2019-08-08 17:43:36,342 [lib.api.process] INFO: 32-bit DLL to inject is C:\mucvbxfoni\dll\cuKCDF.dll, loader C:\mucvbxfoni\bin\YGwQISq.exe
> 2019-08-08 17:43:36,390 [root] DEBUG: ReadConfig: Successfully loaded pipe name \\.\PIPE\KqHrJn.
> 2019-08-08 17:43:36,405 [root] DEBUG: Loader: Injecting process 2896 (thread 2900) with C:\mucvbxfoni\dll\cuKCDF.dll.
> 2019-08-08 17:43:36,405 [root] DEBUG: Process image base: 0x009B0000
> 2019-08-08 17:43:36,405 [root] DEBUG: InjectDllViaIAT: IAT patching with dll name C:\mucvbxfoni\dll\cuKCDF.dll.
> 2019-08-08 17:43:36,405 [root] DEBUG: InjectDllViaIAT: Found a free region from 0x00A56000 - 0x76E20000
> 2019-08-08 17:43:36,421 [root] DEBUG: InjectDllViaIAT: Allocated 0x218 bytes for new import table at 0x00A60000.
> 2019-08-08 17:43:36,421 [root] DEBUG: InjectDllViaIAT: Successfully patched IAT.
> 2019-08-08 17:43:36,421 [root] DEBUG: Successfully injected DLL C:\mucvbxfoni\dll\cuKCDF.dll.
> 2019-08-08 17:43:36,437 [lib.api.process] INFO: Injected into suspended 32-bit process with pid 2896
> 2019-08-08 17:43:38,437 [lib.api.process] INFO: Successfully resumed process with pid 2896
> 2019-08-08 17:43:38,453 [root] INFO: Added new process to list with pid: 2896
> 2019-08-08 17:43:38,467 [root] DEBUG: Terminate processes on terminate_event disabled.
> 2019-08-08 17:43:38,467 [root] DEBUG: CAPE debug - unrecognised key nohuman.
> 2019-08-08 17:43:38,483 [root] DEBUG: Process dumps enabled.
> 2019-08-08 17:43:38,530 [root] DEBUG: RestoreHeaders: Restored original import table.
> 2019-08-08 17:43:38,530 [root] INFO: Disabling sleep skipping.
> 2019-08-08 17:43:38,546 [root] INFO: Disabling sleep skipping.
> 2019-08-08 17:43:38,546 [root] INFO: Disabling sleep skipping.
> 2019-08-08 17:43:38,546 [root] INFO: Disabling sleep skipping.
> 2019-08-08 17:43:38,546 [root] DEBUG: CAPE initialised: 32-bit base package loaded in process 2896 at 0x73a40000, image base 0x9b0000, stack from 0x142000-0x150000
> 2019-08-08 17:43:38,562 [root] DEBUG: Commandline: C:\Users\IEUser\AppData\Local\Temp\"C:\Program Files (x86)\Internet Explorer\iexplore.exe" "textspeier[.]de".
> 2019-08-08 17:43:38,562 [root] INFO: Monitor successfully loaded in process with pid 2896.
> 2019-08-08 17:43:38,578 [root] DEBUG: DLL unloaded from 0x76320000.
> 2019-08-08 17:43:38,608 [root] DEBUG: DLL loaded at 0x72660000: C:\Windows\system32\IEFRAME (0xa80000 bytes).
> 2019-08-08 17:43:38,625 [root] DEBUG: DLL loaded at 0x73A00000: C:\Windows\system32\OLEACC (0x3c000 bytes).
> 2019-08-08 17:43:38,671 [root] DEBUG: DLL loaded at 0x73860000: C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.17514_none_41e6975e2bd6f2b2\comctl32 (0x19e000 bytes).
> 2019-08-08 17:43:38,733 [root] DEBUG: DLL loaded at 0x73850000: C:\Windows\system32\profapi (0xb000 bytes).
> 2019-08-08 17:43:38,765 [root] DEBUG: DLL loaded at 0x73B10000: C:\Windows\system32\ntmarta (0x21000 bytes).
> 2019-08-08 17:43:38,765 [root] DEBUG: DLL loaded at 0x76020000: C:\Windows\syswow64\WLDAP32 (0x45000 bytes).
> 2019-08-08 17:43:38,780 [root] DEBUG: DLL loaded at 0x74F90000: C:\Windows\syswow64\ws2_32 (0x35000 bytes).
> 2019-08-08 17:43:38,780 [root] DEBUG: DLL loaded at 0x74EC0000: C:\Windows\syswow64\NSI (0x6000 bytes).
> 2019-08-08 17:43:38,780 [root] DEBUG: DLL loaded at 0x74A20000: C:\Windows\system32\dnsapi (0x44000 bytes).
> 2019-08-08 17:43:38,796 [root] DEBUG: DLL loaded at 0x73830000: C:\Windows\system32\iphlpapi (0x1c000 bytes).
> 2019-08-08 17:43:38,796 [root] DEBUG: DLL loaded at 0x73820000: C:\Windows\system32\WINNSI (0x7000 bytes).
> 2019-08-08 17:43:38,828 [root] DEBUG: DLL loaded at 0x75F40000: C:\Windows\syswow64\CLBCatQ (0x83000 bytes).
> 2019-08-08 17:43:38,828 [root] DEBUG: DLL loaded at 0x72600000: C:\Windows\System32\netprofm (0x5a000 bytes).
> 2019-08-08 17:43:38,842 [root] DEBUG: DLL loaded at 0x74AA0000: C:\Windows\System32\nlaapi (0x10000 bytes).
> 2019-08-08 17:43:38,858 [root] DEBUG: DLL loaded at 0x73120000: C:\Windows\system32\CRYPTSP (0x16000 bytes).
> 2019-08-08 17:43:38,858 [root] DEBUG: DLL loaded at 0x730E0000: C:\Windows\system32\rsaenh (0x3b000 bytes).
> 2019-08-08 17:43:38,875 [root] DEBUG: DLL loaded at 0x73810000: C:\Windows\system32\RpcRtRemote (0xe000 bytes).
> 2019-08-08 17:43:38,890 [root] DEBUG: DLL loaded at 0x73800000: C:\Windows\System32\npmproxy (0x8000 bytes).
> 2019-08-08 17:43:38,905 [root] DEBUG: DLL unloaded from 0x76B50000.
> 2019-08-08 17:43:38,905 [root] DEBUG: DLL unloaded from 0x73800000.
> 2019-08-08 17:43:38,921 [root] DEBUG: DLL unloaded from 0x72600000.
> 2019-08-08 17:43:38,937 [root] DEBUG: DLL loaded at 0x76810000: C:\Windows\syswow64\comdlg32 (0x7b000 bytes).
> 2019-08-08 17:43:38,937 [root] DEBUG: DLL loaded at 0x73BE0000: C:\Windows\system32\uxtheme (0x80000 bytes).
> 2019-08-08 17:43:38,953 [root] DEBUG: DLL unloaded from 0x73BE0000.
> 2019-08-08 17:43:38,953 [root] DEBUG: DLL loaded at 0x72620000: C:\Program Files (x86)\Internet Explorer\sqmapi (0x33000 bytes).
> 2019-08-08 17:43:38,967 [root] DEBUG: DLL unloaded from 0x74D90000.
> 2019-08-08 17:43:38,967 [root] DEBUG: DLL unloaded from 0x76070000.
> 2019-08-08 17:43:38,967 [root] DEBUG: DLL unloaded from 0x72620000.
> 2019-08-08 17:43:38,983 [root] DEBUG: DLL unloaded from 0x77000000.
> 2019-08-08 17:43:39,000 [root] DEBUG: DLL loaded at 0x737F0000: C:\Windows\system32\dwmapi (0x13000 bytes).
> 2019-08-08 17:43:39,155 [root] DEBUG: DLL loaded at 0x73CC0000: C:\Windows\system32\apphelp (0x4c000 bytes).
> 2019-08-08 17:43:39,171 [root] DEBUG: DLL loaded at 0x737E0000: C:\Windows\system32\VERSION (0x9000 bytes).
> 2019-08-08 17:43:39,171 [root] DEBUG: DLL unloaded from 0x75DF0000.
> 2019-08-08 17:43:39,203 [root] DEBUG: DLL unloaded from 0x009B0000.
> 2019-08-08 17:43:39,217 [root] INFO: Announced 32-bit process name: iexplore.exe pid: 2300
> 2019-08-08 17:43:39,217 [lib.api.process] INFO: Option 'nohuman' with value 'yes' sent to monitor
> 2019-08-08 17:43:39,233 [lib.api.process] INFO: Option 'procdump' with value '1' sent to monitor
> 2019-08-08 17:43:39,233 [lib.api.process] INFO: 32-bit DLL to inject is C:\mucvbxfoni\dll\cuKCDF.dll, loader C:\mucvbxfoni\bin\YGwQISq.exe
> 2019-08-08 17:43:39,250 [root] DEBUG: ReadConfig: Successfully loaded pipe name \\.\PIPE\KqHrJn.
> 2019-08-08 17:43:39,265 [root] DEBUG: Loader: Injecting process 2300 (thread 2296) with C:\mucvbxfoni\dll\cuKCDF.dll.
> 2019-08-08 17:43:39,265 [root] DEBUG: Process image base: 0x009B0000
> 2019-08-08 17:43:39,265 [root] DEBUG: InjectDllViaIAT: IAT patching with dll name C:\mucvbxfoni\dll\cuKCDF.dll.
> 2019-08-08 17:43:39,280 [root] DEBUG: InjectDllViaIAT: Found a free region from 0x00A56000 - 0x76E20000
> 2019-08-08 17:43:39,296 [root] DEBUG: InjectDllViaIAT: Allocated 0x218 bytes for new import table at 0x00A60000.
> 2019-08-08 17:43:39,296 [root] DEBUG: InjectDllViaIAT: Successfully patched IAT.
> 2019-08-08 17:43:39,312 [root] DEBUG: Successfully injected DLL C:\mucvbxfoni\dll\cuKCDF.dll.
> 2019-08-08 17:43:39,328 [lib.api.process] INFO: Injected into suspended 32-bit process with pid 2300
> 2019-08-08 17:43:39,342 [root] DEBUG: Terminate processes on terminate_event disabled.
> 2019-08-08 17:43:39,358 [root] DEBUG: CAPE debug - unrecognised key nohuman.
> 2019-08-08 17:43:39,358 [root] DEBUG: DLL loaded at 0x72600000: C:\Windows\system32\RASAPI32 (0x52000 bytes).
> 2019-08-08 17:43:39,358 [root] DEBUG: Process dumps enabled.
> 2019-08-08 17:43:39,375 [root] INFO: Disabling sleep skipping.
> 2019-08-08 17:43:39,375 [root] DEBUG: DLL loaded at 0x725E0000: C:\Windows\system32\rasman (0x15000 bytes).
> 2019-08-08 17:43:39,390 [root] DEBUG: RestoreHeaders: Restored original import table.
> 2019-08-08 17:43:39,390 [root] DEBUG: CAPE initialised: 32-bit base package loaded in process 2300 at 0x73a40000, image base 0x9b0000, stack from 0x3b2000-0x3c0000
> 2019-08-08 17:43:39,390 [root] DEBUG: DLL loaded at 0x725D0000: C:\Windows\system32\rtutils (0xd000 bytes).
> 2019-08-08 17:43:39,405 [root] DEBUG: Commandline: C:\Users\IEUser\Desktop\"C:\Program Files (x86)\Internet Explorer\iexplore.exe" SCODEF:2896 CREDAT:79873.
> 2019-08-08 17:43:39,405 [root] INFO: Added new process to list with pid: 2300
> 2019-08-08 17:43:39,405 [root] DEBUG: DLL unloaded from 0x72600000.
> 2019-08-08 17:43:39,405 [root] INFO: Monitor successfully loaded in process with pid 2300.
> 2019-08-08 17:43:39,405 [root] DEBUG: DLL unloaded from 0x725E0000.
> 2019-08-08 17:43:39,405 [root] DEBUG: DLL unloaded from 0x74BC0000.
> 2019-08-08 17:43:39,405 [root] DEBUG: DLL unloaded from 0x76320000.
> 2019-08-08 17:43:39,421 [root] DEBUG: DLL loaded at 0x725C0000: C:\Windows\system32\sensapi (0x6000 bytes).
> 2019-08-08 17:43:39,421 [root] DEBUG: DLL loaded at 0x72660000: C:\Windows\system32\IEFRAME (0xa80000 bytes).
> 2019-08-08 17:43:39,421 [root] DEBUG: DLL loaded at 0x74AA0000: C:\Windows\system32\NLAapi (0x10000 bytes).
> 2019-08-08 17:43:39,421 [root] DEBUG: DLL unloaded from 0x725E0000.
> 2019-08-08 17:43:39,437 [root] DEBUG: DLL loaded at 0x73A00000: C:\Windows\system32\OLEACC (0x3c000 bytes).
> 2019-08-08 17:43:39,437 [root] DEBUG: DLL loaded at 0x73860000: C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.7601.17514_none_41e6975e2bd6f2b2\comctl32 (0x19e000 bytes).
> 2019-08-08 17:43:39,437 [root] DEBUG: DLL loaded at 0x76810000: C:\Windows\syswow64\comdlg32 (0x7b000 bytes).
> 2019-08-08 17:43:39,437 [root] DEBUG: DLL loaded at 0x725B0000: C:\Windows\system32\rasadhlp (0x6000 bytes).
> 2019-08-08 17:43:39,453 [root] DEBUG: DLL loaded at 0x74A90000: C:\Windows\system32\napinsp (0x10000 bytes).
> 2019-08-08 17:43:39,453 [root] DEBUG: DLL loaded at 0x72570000: C:\Program Files (x86)\Internet Explorer\IEShims (0x35000 bytes).
> 2019-08-08 17:43:39,467 [root] DEBUG: DLL loaded at 0x74A70000: C:\Windows\system32\pnrpnsp (0x12000 bytes).
> 2019-08-08 17:43:39,467 [root] DEBUG: DLL loaded at 0x74AC0000: C:\Windows\System32\mswsock (0x3c000 bytes).
> 2019-08-08 17:43:39,467 [root] DEBUG: DLL loaded at 0x74A10000: C:\Windows\System32\winrnr (0x8000 bytes).
> 2019-08-08 17:43:39,467 [root] DEBUG: DLL loaded at 0x74AB0000: C:\Windows\System32\wshtcpip (0x5000 bytes).
> 2019-08-08 17:43:39,483 [root] DEBUG: DLL loaded at 0x73BE0000: C:\Windows\system32\uxtheme (0x80000 bytes).
> 2019-08-08 17:43:39,483 [root] DEBUG: DLL unloaded from 0x73BE0000.
> 2019-08-08 17:43:39,483 [root] DEBUG: DLL loaded at 0x72560000: C:\Windows\System32\wship6 (0x6000 bytes).
> 2019-08-08 17:43:39,500 [root] DEBUG: DLL loaded at 0x73810000: C:\Windows\system32\RpcRtRemote (0xe000 bytes).
> 2019-08-08 17:43:39,500 [root] DEBUG: DLL loaded at 0x72520000: C:\Windows\System32\fwpuclnt (0x38000 bytes).
> 2019-08-08 17:43:39,500 [root] INFO: Announced 64-bit process name: explorer.exe pid: 1772
> 2019-08-08 17:43:39,515 [root] DEBUG: DLL loaded at 0x737F0000: C:\Windows\system32\dwmapi (0x13000 bytes).
> 2019-08-08 17:43:39,515 [lib.api.process] INFO: Option 'nohuman' with value 'yes' sent to monitor
> 2019-08-08 17:43:39,515 [lib.api.process] INFO: Option 'procdump' with value '1' sent to monitor
> 2019-08-08 17:43:39,515 [root] DEBUG: DLL loaded at 0x724C0000: C:\Windows\System32\netprofm (0x5a000 bytes).
> 2019-08-08 17:43:39,515 [lib.api.process] INFO: 64-bit DLL to inject is C:\mucvbxfoni\dll\txiNFP.dll, loader C:\mucvbxfoni\bin\sIoHcZyd.exe
> 2019-08-08 17:43:39,515 [root] DEBUG: DLL loaded at 0x72480000: C:\Program Files (x86)\Internet Explorer\sqmapi (0x33000 bytes).
> 2019-08-08 17:43:39,515 [root] DEBUG: DLL unloaded from 0x74D90000.
> 2019-08-08 17:43:39,530 [root] DEBUG: DLL loaded at 0x72470000: C:\Windows\System32\npmproxy (0x8000 bytes).
> 2019-08-08 17:43:39,530 [root] DEBUG: DLL unloaded from 0x76070000.
> 2019-08-08 17:43:39,530 [root] DEBUG: DLL unloaded from 0x72480000.
> 2019-08-08 17:43:39,530 [root] DEBUG: ReadConfig: Successfully loaded pipe name \\.\PIPE\KqHrJn.
> 2019-08-08 17:43:39,530 [root] DEBUG: Loader: Injecting process 1772 (thread 0) with C:\mucvbxfoni\dll\txiNFP.dll.
> 2019-08-08 17:43:39,530 [root] DEBUG: InjectDll: No thread ID supplied, GetProcessInitialThreadId failed.
> 2019-08-08 17:43:39,546 [root] DEBUG: DLL loaded at 0x724A0000: C:\Windows\system32\DHCPCSVC (0x12000 bytes).
> 2019-08-08 17:43:39,546 [root] DEBUG: DLL loaded at 0x75F40000: C:\Windows\syswow64\CLBCatQ (0x83000 bytes).
> 2019-08-08 17:43:39,546 [root] DEBUG: Terminate processes on terminate_event disabled.
> 2019-08-08 17:43:39,562 [root] DEBUG: CAPE debug - unrecognised key nohuman.
> 2019-08-08 17:43:39,562 [root] DEBUG: DLL loaded at 0x72290000: C:\Windows\system32\propsys (0xf5000 bytes).
> 2019-08-08 17:43:39,562 [root] DEBUG: Process dumps enabled.
> 2019-08-08 17:43:39,562 [root] DEBUG: DLL loaded at 0x72490000: C:\Windows\system32\dhcpcsvc6 (0xd000 bytes).
> 2019-08-08 17:43:39,562 [root] INFO: Disabling sleep skipping.
> 2019-08-08 17:43:39,578 [root] DEBUG: DLL unloaded from 0x73830000.
> 2019-08-08 17:43:39,578 [root] DEBUG: DLL loaded at 0x76180000: C:\Windows\syswow64\SETUPAPI (0x19d000 bytes).
> 2019-08-08 17:43:39,578 [root] DEBUG: DLL unloaded from 0x724A0000.
> 2019-08-08 17:43:39,592 [root] DEBUG: DLL loaded at 0x76620000: C:\Windows\syswow64\CFGMGR32 (0x27000 bytes).
> 2019-08-08 17:43:39,592 [root] DEBUG: DLL loaded at 0x76BE0000: C:\Windows\syswow64\DEVOBJ (0x12000 bytes).
> 2019-08-08 17:43:39,592 [root] WARNING: Unable to place hook on LockResource
> 2019-08-08 17:43:39,592 [root] WARNING: Unable to hook LockResource
> 2019-08-08 17:43:39,608 [root] DEBUG: DLL loaded at 0x73B10000: C:\Windows\system32\ntmarta (0x21000 bytes).
> 2019-08-08 17:43:39,608 [root] DEBUG: DLL loaded at 0x76020000: C:\Windows\syswow64\WLDAP32 (0x45000 bytes).
> 2019-08-08 17:43:39,625 [root] DEBUG: DLL unloaded from 0x74FD0000.
> 2019-08-08 17:43:39,625 [root] DEBUG: CAPE initialised: 64-bit base package loaded in process 1772 at 0x0000000072390000, image base 0x00000000FF320000, stack from 0x00000000049D2000-0x00000000049E0000
> 2019-08-08 17:43:39,625 [root] DEBUG: Commandline: C:\Windows\explorer.exe.
> 2019-08-08 17:43:39,640 [root] INFO: Added new process to list with pid: 1772
> 2019-08-08 17:43:39,640 [root] INFO: Monitor successfully loaded in process with pid 1772.
> 2019-08-08 17:43:39,640 [root] DEBUG: InjectDllViaThread: Successfully injected Dll into process via RtlCreateUserThread.
> 2019-08-08 17:43:39,640 [root] DEBUG: InjectDll: Successfully injected DLL via thread.
> 2019-08-08 17:43:39,640 [root] DEBUG: Successfully injected DLL C:\mucvbxfoni\dll\txiNFP.dll.
> 2019-08-08 17:43:39,640 [root] DEBUG: DLL loaded at 0x73850000: C:\Windows\system32\profapi (0xb000 bytes).
> 2019-08-08 17:43:39,655 [root] DEBUG: DLL loaded at 0x72260000: C:\Windows\system32\IEUI (0x2d000 bytes).
> 2019-08-08 17:43:39,671 [root] DEBUG: DLL loaded at 0x72480000: C:\Windows\system32\MSIMG32 (0x5000 bytes).
> 2019-08-08 17:44:20,530 [root] DEBUG: set_caller_info: Adding region at 0x000007FEF3EA0000 to caller regions list (advapi32::RegOpenKeyExW).
> 2019-08-08 17:44:20,546 [root] DEBUG: DLL loaded at 0x000007FEF4B30000: C:\Windows\System32\wscinterop (0x28000 bytes).
> 2019-08-08 17:44:20,562 [root] DEBUG: DLL loaded at 0x000007FEF4B10000: C:\Windows\System32\WSCAPI (0x13000 bytes).
> 2019-08-08 17:44:20,578 [root] DEBUG: DLL loaded at 0x000007FEF3A10000: C:\Windows\System32\wscui.cpl (0x11f000 bytes).
> 2019-08-08 17:44:20,592 [root] DEBUG: set_caller_info: Adding region at 0x000007FEF4B10000 to caller regions list (kernel32::GetSystemTimeAsFileTime).
> 2019-08-08 17:44:20,592 [root] DEBUG: set_caller_info: Adding region at 0x000007FEF3A10000 to caller regions list (kernel32::GetSystemTimeAsFileTime).
> 2019-08-08 17:44:20,608 [root] DEBUG: set_caller_info: Adding region at 0x000007FEF4B30000 to caller regions list (kernel32::GetSystemTimeAsFileTime).
> 2019-08-08 17:44:20,655 [root] DEBUG: DLL loaded at 0x000007FEF38D0000: C:\Windows\System32\werconcpl (0x13c000 bytes).
> 2019-08-08 17:44:20,687 [root] DEBUG: DLL loaded at 0x000007FEF4390000: C:\Windows\System32\framedynos (0x4c000 bytes).
> 2019-08-08 17:44:20,703 [root] DEBUG: DLL loaded at 0x000007FEF4AF0000: C:\Windows\System32\wercplsupport (0x19000 bytes).
> 2019-08-08 17:44:20,703 [root] DEBUG: set_caller_info: Adding region at 0x000007FEF4390000 to caller regions list (kernel32::GetSystemTimeAsFileTime).
> 2019-08-08 17:44:20,717 [root] DEBUG: set_caller_info: Adding region at 0x000007FEF4AF0000 to caller regions list (kernel32::GetSystemTimeAsFileTime).
> 2019-08-08 17:44:20,717 [root] DEBUG: set_caller_info: Adding region at 0x000007FEF38D0000 to caller regions list (kernel32::GetSystemTimeAsFileTime).
> 2019-08-08 17:44:20,733 [root] DEBUG: DLL loaded at 0x000007FEF4AC0000: C:\Windows\System32\hcproviders (0xb000 bytes).
> 2019-08-08 17:44:20,750 [root] DEBUG: set_caller_info: Adding region at 0x000007FEF4AC0000 to caller regions list (kernel32::GetSystemTimeAsFileTime).
> 2019-08-08 17:44:20,765 [root] DEBUG: set_caller_info: Adding region at 0x000007FEFC840000 to caller regions list (msvcrt::memcpy).
> 2019-08-08 17:44:40,217 [root] DEBUG: set_caller_info: Adding region at 0x000007FEFDF30000 to caller regions list (ntdll::NtClose).
> 2019-08-08 17:44:43,108 [root] DEBUG: DLL unloaded from 0x000007FEFDB80000.
> 2019-08-08 17:46:57,453 [root] INFO: Analysis timeout hit (200 seconds), terminating analysis.
> 2019-08-08 17:46:57,453 [root] INFO: Created shutdown mutex.
> 2019-08-08 17:46:58,453 [lib.api.process] INFO: Successfully received reply to terminate_event, pid 2896
> 2019-08-08 17:46:58,453 [root] INFO: Terminate event set for process 2896.
> 2019-08-08 17:46:58,453 [lib.api.process] INFO: Successfully received reply to terminate_event, pid 2300
> 2019-08-08 17:46:58,453 [root] DEBUG: Terminate Event: Attempting to dump process 2300
> 2019-08-08 17:46:58,453 [root] INFO: Terminate event set for process 2300.
> 2019-08-08 17:46:58,467 [lib.api.process] INFO: Successfully received reply to terminate_event, pid 1772
> 2019-08-08 17:46:58,467 [root] DEBUG: DumpInterestingRegions: Dumping Imagebase at 0x009B0000.
> 2019-08-08 17:46:58,467 [root] INFO: Terminate event set for process 1772.
> 2019-08-08 17:46:58,467 [root] DEBUG: Terminate Event: Attempting to dump process 1772
> 2019-08-08 17:46:58,483 [root] INFO: Shutting down package.
> 2019-08-08 17:46:58,483 [root] DEBUG: DumpProcess: Instantiating PeParser with address: 0x009B0000.
> 2019-08-08 17:46:58,500 [root] INFO: Stopping auxiliary modules.
> 2019-08-08 17:46:58,500 [root] DEBUG: DumpProcess: Module entry point VA is 0x00001C9A.
> 2019-08-08 17:46:58,500 [root] INFO: Finishing auxiliary modules.
> 2019-08-08 17:46:58,500 [root] DEBUG: DumpInterestingRegions: Dumping Imagebase at 0x00000000FF320000.
> 2019-08-08 17:46:58,500 [root] INFO: Shutting down pipe server and dumping dropped files.
> 2019-08-08 17:46:58,515 [root] WARNING: File at path "C:\irYjEH\debugger" does not exist, skip.
> 2019-08-08 17:46:58,515 [root] DEBUG: DumpProcess: Instantiating PeParser with address: 0x00000000FF320000.
> 2019-08-08 17:46:58,515 [root] INFO: Analysis completed.
> 2019-08-08 17:46:58,515 [root] DEBUG: DumpProcess: Module entry point VA is 0x000000000002B790.
> 2019-08-08 17:46:58,578 [root] INFO: Added new CAPE file to list with path: C:\irYjEH\CAPE\2300_19411634245846178482019
> 2019-08-08 17:46:58,578 [root] DEBUG: DumpProcess: Module image dump success - dump size 0xa2a00.

**Comment by kevoreilly** [comment] 2019-08-09 09:39
Hmm very strange - I have no idea why the submissions would fail like this and get stuck on an older URL. All I can think of suggesting is to check the server-side log as it seems more likely a problem between web server and cape server than between server and target vm. Could you check logs/cuckoo.log for these different submissions and let me know if there is anything there that might help shed some light.

**Comment by kevoreilly** [comment] 2019-08-09 10:09
Also, it would be worth checking whether the issue is reproduceable on https://cape.contextis.com.

**Comment by doomedraven** [comment] 2019-08-09 10:34
also check the db to see that really different urls was added

**Comment by KindaTerrible** [comment] 2019-08-09 11:50
@kevoreilly Thanks for having me check log/cuckoo.log

Having investigating these logs, I noticed the following.

> 2019-08-09 04:25:44,056 [lib.cuckoo.core.scheduler] INFO: Task #1: Starting analysis of URL '**raneevahijab[.]id/adnin/box/workspace/**'
> 2019-08-09 04:25:44,057 [lib.cuckoo.core.scheduler] ERROR: Task #1: **Analysis results folder already exists at path '/home/infected/CAPE/storage/analyses/1', analysis aborted**

So this led me to discover that when you delete a task via the web server it does not delete the folder(s) associated with it on the back end. So when running a new task that is assigned a previous/old Task ID it aborts the analysis and returns the results of the old task.

I confirmed this by running a couple more tasks until I finally got the new test URL analyzed after clearing all the previously old tasks (I could of deleted the old task folders and most likely have ran the new URL without error too).

**Comment by doomedraven** [comment] 2019-08-09 11:51
feel free to provide PR for correct deletion, not only in mongo but also path

**Comment by doomedraven** [comment] 2019-08-20 05:53
this will fix your problem https://github.com/kevoreilly/CAPE/pull/55

**Comment by kevoreilly** [comment] 2019-08-22 10:53
Ok that should be merged now - thanks as ever doomedraven.

I will hold off for a while to allow it to be tested then I'll close this unless I hear otherwise.

**Closed** 2019-09-15 20:57 UTC
