### ISSUE TITLE
dump-on-api failed with The specified rule file at CAPE doesn't exist, skip

### ISSUE THREAD

**Issue by He1loC** [ctxis/CAPE#392] opened 2019-08-27 09:39 UTC
2019-08-27 17:34:34,752 [modules.processing.CAPE] INFO: CAPE: UPX - Statically unpacked binary /tmp/tmprrgeE9.
2019-08-27 17:34:34,754 [lib.cuckoo.common.objects] WARNING: The specified rule file at CAPE doesn't exist, skip
2019-08-27 17:34:34,803 [modules.processing.CAPE] INFO: CAPE: Found UPX Packed sample - attempting to unpack
2019-08-27 17:34:34,946 [modules.processing.CAPE] INFO: CAPE: UPX - Statically unpacked binary /tmp/tmpyCFzmc.
2019-08-27 17:34:34,948 [lib.cuckoo.common.objects] WARNING: The specified rule file at CAPE doesn't exist, skip
2019-08-27 17:34:34,994 [modules.processing.CAPE] INFO: CAPE: Found UPX Packed sample - attempting to unpack
2019-08-27 17:34:35,140 [modules.processing.CAPE] INFO: CAPE: UPX - Statically unpacked binary /tmp/tmprICyLw.
2019-08-27 17:34:35,142 [lib.cuckoo.common.objects] WARNING: The specified rule file at CAPE doesn't exist, skip
2019-08-27 17:34:35,188 [modules.processing.CAPE] INFO: CAPE: Found UPX Packed sample - attempting to unpack
2019-08-27 17:34:35,332 [modules.processing.CAPE] INFO: CAPE: UPX - Statically unpacked binary /tmp/tmprA568q.
2019-08-27 17:34:35,335 [lib.cuckoo.common.objects] WARNING: The specified rule file at CAPE doesn't exist, skip

using UPX1.2
works fine on https://cape.contextis.com/
but failed running locally
help!!

**Comment by doomedraven** [comment] 2019-08-27 09:40
do you have enabled to remove origin files in cuckoo.conf?

**Comment by He1loC** [comment] 2019-08-27 09:42
> do you have enabled to remove origin files in cuckoo.conf?

no,delete_original = off

**Comment by doomedraven** [comment] 2019-08-27 09:54
could you specify how to reproduce it?

**Comment by kevoreilly** [comment] 2019-08-27 16:13
Hmm I wonder if it's looking for a yara sig in data/yara/CAPE...

**Comment by kevoreilly** [comment] 2019-09-11 17:53
I'm still not sure if I understand the what the issue is here - any chance you could clarify?

**Comment by kevoreilly** [comment] 2019-09-14 09:57
I'm going to close this soon - not even sure I understand the issue, without feedback there is no way we can help.

For what it's worth, the dump-on-api option is intended for use with the DumpOnAPI package, in order to dump a payload from malware at the moment that it first calls the API you supplied. It's designed for unpacking malware where one the first API calls of the unpacked code can hopefully be used to get a freshly unpacked sample before it has run too much.

**Closed** 2019-09-15 20:49 UTC
